override-dependencies = [
    "cuda-bindings; sys_platform == 'never'",
    "cuda-pathfinder; sys_platform == 'never'",
    "flash-attn; sys_platform == 'never'",
    "nvidia-cublas; sys_platform == 'never'",
    "nvidia-cuda-cupti; sys_platform == 'never'",
    "nvidia-cuda-nvrtc; sys_platform == 'never'",
    "nvidia-cuda-runtime; sys_platform == 'never'",
    "nvidia-cudnn-cu13; sys_platform == 'never'",
    "nvidia-cufft; sys_platform == 'never'",
    "nvidia-cufile; sys_platform == 'never'",
    "nvidia-curand; sys_platform == 'never'",
    "nvidia-cusolver; sys_platform == 'never'",
    "nvidia-cusparse; sys_platform == 'never'",
    "nvidia-cusparselt-cu13; sys_platform == 'never'",
    "nvidia-nccl-cu13; sys_platform == 'never'",
    "nvidia-nvjitlink; sys_platform == 'never'",
    "nvidia-nvshmem-cu13; sys_platform == 'never'",
    "nvidia-nvtx; sys_platform == 'never'",
    "torch; sys_platform == 'never'",
    "torchao; sys_platform == 'never'",
    "torchcodec; sys_platform == 'never'",
    "torchvision; sys_platform == 'never'",
    "transformer-engine; sys_platform == 'never'",
    "transformer-engine-cu13; sys_platform == 'never'",
    "transformer-engine-torch; sys_platform == 'never'",
    "triton; sys_platform == 'never'",
]
