# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Benchmarking config for GLM-5 Te Deepep

# To run this recipe:
#   automodel examples/llm_benchmark/glm/glm_5_te_deepep.yaml --nproc-per-node 8
# Adjust --nproc-per-node to the number of GPUs available on your machine.

recipe: BenchmarkingRecipeForNextTokenPrediction

seed: 1234

benchmark:
  warmup_steps: 2
  peak_tflops: 989  # H100 peak TFLOPs
  nsys_start: -1
  nsys_end: -1
  nsys_ranks: []
  num_nodes: 128

step_scheduler:
  gc_every_steps: 10
  global_batch_size: 1024
  local_batch_size: 4
  ckpt_every_steps: 1000
  val_every_steps: 1000
  num_epochs: 1
  max_steps: 12

distributed:
  strategy: fsdp2
  tp_size: 1
  cp_size: 1
  pp_size: 4
  ep_size: 64

  sequence_parallel: false
  activation_checkpointing: true

  pipeline:
    pp_schedule: interleaved1f1b
    pp_microbatch_size: 1
    round_virtual_stages_to_pp_multiple: down
    scale_grads_in_schedule: false
    patch_inner_model: false
    patch_causal_lm_model: false
    layers_per_stage: 2

  moe:
    reshard_after_forward: false
    wrap_outer_model: false

dist_env:
  backend: nccl
  timeout_minutes: 10

model:
  _target_: nemo_automodel.NeMoAutoModelForCausalLM.from_config
  config:
    _target_: transformers.AutoConfig.from_pretrained
    pretrained_model_name_or_path: zai-org/GLM-5
  trust_remote_code: true
  backend:
    _target_: nemo_automodel.components.models.common.BackendConfig
    attn: te
    linear: te
    rms_norm: te
    rope_fusion: false
    experts: torch_mm
    dispatcher: hybridep
    fake_balanced_gate: true
    enable_hf_state_dict_adapter: true
    enable_fsdp_optimizations: true

checkpoint:
  enabled: false

loss_fn:
  _target_: nemo_automodel.components.loss.masked_ce.MaskedCrossEntropy
  fp32_upcast: false

dataset:
  _target_: nemo_automodel.components.datasets.llm.mock_iterable_dataset.MockIterableDataset
  seq_len: 4096
  num_samples: 100000

dataloader:
  batch_size: null  # Dataset already yields batches
  _target_: torch.utils.data.DataLoader
  num_workers: 0

optimizer:
  _target_: torch.optim.Adam
  betas:
  - 0.9
  - 0.999
  eps: 1e-8
  lr: 0.0001
  weight_decay: 0

ci:
  time: "00:45:00"
  nodes: 128
  env_vars:
    PYTORCH_CUDA_ALLOC_CONF: "expandable_segments:True"
