# Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Regenerate dataset answers with the EAGLE target model.

EAGLE drafters learn best when the supervised assistant turn is produced by
the *same* model that will serve as the inference target. Many public chat
datasets were generated by other models, so the assistant tokens they contain
are off-distribution for the drafter. This script takes such a dataset,
strips the trailing assistant turn from each sample, replays the remaining
``[system, user, ...]`` context against a target model running behind an
OpenAI-compatible SGLang server, and writes a new dataset whose
``messages`` column ends with a freshly-generated assistant turn.

The output parquet files have the same ``messages`` column shape that
``ChatDataset`` (used by ``build_eagle3_dataloader``) consumes, so the
regenerated directory can be plugged directly into ``train_data_path`` in
the EAGLE-3 recipe.

Typical usage:

    # 1. Spin up SGLang serving the target model in another shell:
    python -m sglang.launch_server \\
        --model-path meta-llama/Llama-3.1-8B-Instruct --port 30000

    # 2. Regenerate answers:
    python -m nemo_automodel.components.speculative.regenerate \\
        --input-data Aeala/ShareGPT_Vicuna_unfiltered \\
        --output-dir ./regenerated/sharegpt_llama31_8b \\
        --target-server http://localhost:30000/v1 \\
        --model meta-llama/Llama-3.1-8B-Instruct \\
        --concurrency 64 --shard-size 1000

The script is resumable: re-running with the same ``--output-dir --resume``
skips any shards that are already on disk, and verifies via a manifest that
the input/model/sharding configuration matches the earlier run.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import logging
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from nemo_automodel.shared.import_utils import safe_import

logger = logging.getLogger(__name__)

_AIOHTTP_INSTALL_HINT = (
    "aiohttp is required for regenerate.py. It is normally pulled in via the "
    "project's dependencies; if you see this message your environment is missing it. "
    "Reinstall with `uv sync` or `uv pip install aiohttp`."
)
_PYARROW_INSTALL_HINT = (
    "pyarrow is required to write regenerated shards as parquet. Install it with "
    "`uv pip install pyarrow` and re-run this script."
)

_SHARD_NAME_RE = re.compile(r"^shard-(\d{6})\.parquet$")
_MANIFEST_NAME = "manifest.json"


@dataclass
class GenerationConfig:
    """Sampling parameters forwarded to the SGLang chat completion endpoint."""

    model: str
    max_new_tokens: int
    temperature: float
    top_p: float
    reasoning: str = "none"


def _build_manifest(args: argparse.Namespace) -> dict[str, Any]:
    """Return the regeneration settings that must stay stable across resume.

    Fields that change the *content* of the output dataset are included. Fields
    that only affect throughput / reliability (``concurrency``, ``timeout_s``,
    ``max_retries``) are intentionally omitted so a user can re-resume with
    different operational knobs. ``output_dir`` is also omitted: the manifest
    lives inside ``output_dir``, so encoding it here would only break resume
    after a directory rename.
    """
    return {
        "input_data": args.input_data,
        "target_server": args.target_server,
        "model": args.model,
        "messages_column": args.messages_column,
        "split": args.split,
        "dataset_name": args.dataset_name,
        "shuffle_seed": args.shuffle_seed,
        "shard_size": args.shard_size,
        "max_new_tokens": args.max_new_tokens,
        "temperature": args.temperature,
        "top_p": args.top_p,
        "reasoning": args.reasoning,
    }


def _manifest_path(output_dir: Path) -> Path:
    """Return the manifest path inside ``output_dir``."""
    return output_dir / _MANIFEST_NAME


def _write_manifest(output_dir: Path, manifest: dict[str, Any]) -> Path:
    """Persist the current regeneration config for future ``--resume`` checks."""
    path = _manifest_path(output_dir)
    tmp_path = path.with_suffix(path.suffix + ".tmp")
    tmp_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    os.replace(tmp_path, path)
    return path


def _ensure_manifest_compatible(
    output_dir: Path,
    manifest: dict[str, Any],
    *,
    resume: bool,
    existing_shards: set[int],
) -> None:
    """Guard ``--resume`` against silently mixing shards from different runs.

    Also refuses to start a fresh run that would silently clobber existing
    shards: if the output directory already contains shard files and the user
    did *not* pass ``--resume``, raise so they make an explicit choice (either
    delete the directory or pass ``--resume``).
    """
    path = _manifest_path(output_dir)
    if not resume:
        if existing_shards:
            raise ValueError(
                f"{output_dir} already contains {len(existing_shards)} shard file(s). "
                "Pass --resume to continue the previous run, or delete the directory to start fresh."
            )
        _write_manifest(output_dir, manifest)
        return

    if not path.exists():
        if existing_shards:
            raise ValueError(
                f"--resume was requested for {output_dir}, but {_MANIFEST_NAME} is missing. "
                "Cannot verify that existing shards were generated from the same input/model/config."
            )
        _write_manifest(output_dir, manifest)
        return

    existing_manifest = json.loads(path.read_text(encoding="utf-8"))
    if existing_manifest != manifest:
        raise ValueError(
            f"--resume was requested for {output_dir}, but {_MANIFEST_NAME} does not match the current run "
            f"configuration.\nexisting={existing_manifest}\ncurrent={manifest}"
        )


def _validate_args(args: argparse.Namespace) -> None:
    """Reject invalid CLI values before any network or disk work starts."""
    if args.concurrency < 1:
        raise ValueError(f"--concurrency must be >= 1, got {args.concurrency}")
    if args.shard_size < 1:
        raise ValueError(f"--shard-size must be >= 1, got {args.shard_size}")
    if args.max_new_tokens < 1:
        raise ValueError(f"--max-new-tokens must be >= 1, got {args.max_new_tokens}")
    if args.max_retries < 0:
        raise ValueError(f"--max-retries must be >= 0, got {args.max_retries}")
    if args.timeout_s <= 0:
        raise ValueError(f"--timeout-s must be > 0, got {args.timeout_s}")


def _import_aiohttp():
    ok, mod = safe_import("aiohttp")
    if not ok:
        logger.error(_AIOHTTP_INSTALL_HINT)
        raise SystemExit(2)
    return mod


def _import_pyarrow_table():
    ok, pa = safe_import("pyarrow")
    if not ok:
        logger.error(_PYARROW_INSTALL_HINT)
        raise SystemExit(2)
    ok, pq = safe_import("pyarrow.parquet")
    if not ok:
        logger.error(_PYARROW_INSTALL_HINT)
        raise SystemExit(2)
    return pa, pq


def _extract_prompt_messages(messages: list[dict[str, Any]]) -> list[dict[str, Any]] | None:
    """Return ``messages`` truncated so its tail is *not* an assistant turn.

    EAGLE-3 supervision needs an assistant turn produced by the target model.
    The strategy here mirrors SpecForge's offline regeneration: keep every
    leading system / user / tool turn (including any intermediate
    user<->assistant rounds), but drop the trailing assistant turn so the
    target can produce a fresh one.

    Returns ``None`` if the sample has no valid prompt context (e.g. it is
    empty, or starts with an assistant turn that gets dropped, leaving
    nothing). Callers should skip such samples.
    """
    if not isinstance(messages, list) or not messages:
        return None

    end = len(messages)
    while end > 0 and isinstance(messages[end - 1], dict) and messages[end - 1].get("role") == "assistant":
        end -= 1
    if end == 0:
        return None

    prompt = messages[:end]
    if not any(isinstance(m, dict) and m.get("role") == "user" for m in prompt):
        return None
    return [dict(m) for m in prompt]


def _existing_shard_indices(output_dir: Path) -> set[int]:
    """Return the set of shard indices already present in ``output_dir``."""
    indices: set[int] = set()
    if not output_dir.exists():
        return indices
    for entry in output_dir.iterdir():
        match = _SHARD_NAME_RE.match(entry.name)
        if match is not None:
            indices.add(int(match.group(1)))
    return indices


def _write_shard(
    output_dir: Path,
    shard_index: int,
    rows: list[dict[str, Any]],
) -> Path:
    """Write a shard atomically (``.tmp`` then ``os.replace``) so partial writes never linger."""
    pa, pq = _import_pyarrow_table()
    shard_path = output_dir / f"shard-{shard_index:06d}.parquet"
    tmp_path = shard_path.with_suffix(shard_path.suffix + ".tmp")
    table = pa.Table.from_pylist(rows)
    pq.write_table(table, tmp_path)
    os.replace(tmp_path, shard_path)
    return shard_path


async def _chat_completion(
    session,
    url: str,
    payload: dict[str, Any],
    *,
    timeout_s: float,
    max_retries: int,
) -> dict[str, Any]:
    """POST ``payload`` to ``url`` and return the assistant message dict, with bounded retries."""
    aiohttp = _import_aiohttp()
    last_err: Exception | None = None
    for attempt in range(max_retries + 1):
        try:
            async with session.post(url, json=payload, timeout=aiohttp.ClientTimeout(total=timeout_s)) as resp:
                if resp.status >= 500 or resp.status == 429:
                    text = await resp.text()
                    raise RuntimeError(f"HTTP {resp.status} from {url}: {text[:200]}")
                resp.raise_for_status()
                data = await resp.json()
                return data["choices"][0]["message"]
        except Exception as exc:  # noqa: BLE001 -- retry any transport / 5xx error
            last_err = exc
            if attempt == max_retries:
                raise
            backoff = min(2.0**attempt, 30.0)
            logger.warning(
                "Chat completion failed (attempt %d/%d): %s; retrying in %.1fs",
                attempt + 1,
                max_retries + 1,
                exc,
                backoff,
            )
            await asyncio.sleep(backoff)
    raise RuntimeError(f"Unreachable: max_retries exhausted without raising. Last error: {last_err}")


async def _regenerate_one(
    session,
    url: str,
    prompt: list[dict[str, Any]],
    gen_cfg: GenerationConfig,
    *,
    timeout_s: float,
    max_retries: int,
) -> list[dict[str, Any]]:
    """Call the target server once and return ``prompt + [assistant]``."""
    payload: dict[str, Any] = {
        "model": gen_cfg.model,
        "messages": prompt,
        "max_tokens": gen_cfg.max_new_tokens,
        "temperature": gen_cfg.temperature,
        "top_p": gen_cfg.top_p,
    }
    if gen_cfg.reasoning == "disable":
        payload["extra_body"] = {"chat_template_kwargs": {"enable_thinking": False}}
    msg = await _chat_completion(session, url, payload, timeout_s=timeout_s, max_retries=max_retries)
    resp_msg: dict[str, Any] = {"role": "assistant", "content": msg.get("content", "")}
    if gen_cfg.reasoning == "save":
        reasoning_content = msg.get("reasoning_content")
        if reasoning_content:
            resp_msg["reasoning_content"] = reasoning_content
    return [*prompt, resp_msg]


async def _process_shard(
    session,
    url: str,
    shard_samples: list[tuple[int, list[dict[str, Any]], list[dict[str, Any]]]],
    gen_cfg: GenerationConfig,
    *,
    concurrency: int,
    timeout_s: float,
    max_retries: int,
) -> list[dict[str, Any]]:
    """Run a single shard's prompts through the target server with bounded concurrency.

    ``shard_samples`` items are ``(global_index, original_messages, prompt_messages)``;
    only the prompt is sent to the server, but both are kept around so the
    written rows can preserve the original for traceability.
    """
    semaphore = asyncio.Semaphore(concurrency)
    results: list[dict[str, Any] | None] = [None] * len(shard_samples)

    async def _worker(slot: int, original: list[dict[str, Any]], prompt: list[dict[str, Any]]):
        async with semaphore:
            new_messages = await _regenerate_one(
                session,
                url,
                prompt,
                gen_cfg,
                timeout_s=timeout_s,
                max_retries=max_retries,
            )
            results[slot] = {
                "messages": new_messages,
                "original_messages": original,
            }

    await asyncio.gather(*[_worker(i, original, prompt) for i, (_, original, prompt) in enumerate(shard_samples)])
    return [r for r in results if r is not None]


def _iter_samples(
    dataset: Any,
    messages_column: str,
) -> Any:
    """Yield rows' ``messages_column`` from an HF dataset or a list of dicts."""
    for row in dataset:
        yield row[messages_column]


async def _run(args: argparse.Namespace) -> int:
    """Async driver: load dataset, regenerate, write shards. Returns a process exit code."""
    aiohttp = _import_aiohttp()
    from nemo_automodel.components.datasets.llm.chat_dataset import _load_openai_messages

    _validate_args(args)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    # Always scan for existing shards: without --resume, a non-empty set must
    # trip the clobber guard below (gating the scan on args.resume would feed
    # the guard an always-empty set and let a fresh run silently overwrite and
    # interleave shards from a previous run).
    existing = _existing_shard_indices(output_dir)
    _ensure_manifest_compatible(
        output_dir,
        _build_manifest(args),
        resume=args.resume,
        existing_shards=existing,
    )

    dataset = _load_openai_messages(
        args.input_data,
        split=args.split,
        name=args.dataset_name,
        shuffle_seed=args.shuffle_seed,
    )
    if existing:
        logger.info("Resume: %d shards already present in %s, will be skipped", len(existing), output_dir)

    gen_cfg = GenerationConfig(
        model=args.model,
        max_new_tokens=args.max_new_tokens,
        temperature=args.temperature,
        top_p=args.top_p,
        reasoning=args.reasoning,
    )
    url = args.target_server.rstrip("/") + "/chat/completions"
    timeout = aiohttp.ClientTimeout(total=args.timeout_s)

    completed = 0
    skipped = 0
    usable_prompts = 0
    shard_samples: list[tuple[int, list[dict[str, Any]], list[dict[str, Any]]]] = []

    async def _flush_shard(shard_index: int) -> None:
        nonlocal completed, shard_samples
        if not shard_samples:
            return
        logger.info("Shard %d: regenerating %d samples", shard_index, len(shard_samples))
        rows = await _process_shard(
            session,
            url,
            shard_samples,
            gen_cfg,
            concurrency=args.concurrency,
            timeout_s=args.timeout_s,
            max_retries=args.max_retries,
        )
        shard_path = _write_shard(output_dir, shard_index, rows)
        completed += 1
        logger.info("Wrote %s (%d rows)", shard_path, len(rows))
        shard_samples = []

    async with aiohttp.ClientSession(timeout=timeout) as session:
        for idx, original in enumerate(_iter_samples(dataset, args.messages_column)):
            prompt = _extract_prompt_messages(original)
            if prompt is None:
                skipped += 1
                continue

            shard_index = usable_prompts // args.shard_size
            if shard_index not in existing:
                shard_samples.append((idx, original, prompt))
            usable_prompts += 1

            if usable_prompts % args.shard_size == 0 and shard_index not in existing:
                await _flush_shard(shard_index)
        if shard_samples:
            await _flush_shard(usable_prompts // args.shard_size)

    if skipped:
        logger.warning("Skipped %d samples with no extractable prompt", skipped)
    if usable_prompts == 0:
        logger.error("No usable prompts after extraction; nothing to regenerate.")
        return 1

    logger.info(
        "Done. wrote=%d skipped_existing=%d skipped_invalid=%d output_dir=%s",
        completed,
        len(existing),
        skipped,
        output_dir,
    )
    return 0


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Regenerate dataset assistant turns with an EAGLE target model.",
    )
    parser.add_argument(
        "--input-data",
        required=True,
        help="HF dataset id or local path (parquet/dir/json/jsonl) with a messages column.",
    )
    parser.add_argument("--output-dir", required=True, help="Directory to write regenerated parquet shards into.")
    parser.add_argument(
        "--target-server",
        default="http://localhost:30000/v1",
        help="OpenAI-compatible base URL of the SGLang server hosting the target model.",
    )
    parser.add_argument(
        "--model",
        required=True,
        help="Model name to send in the chat completion payload (must match the SGLang --served-model-name).",
    )
    parser.add_argument(
        "--messages-column", default="messages", help="Column name holding the OpenAI-style messages list."
    )
    parser.add_argument(
        "--split", default="train", help="HF dataset split (supports slice syntax like 'train[:1000]')."
    )
    parser.add_argument("--dataset-name", default=None, help="HF dataset configuration name, if any.")
    parser.add_argument(
        "--shuffle-seed", type=int, default=None, help="Optional shuffle seed applied before slicing the split."
    )
    parser.add_argument("--shard-size", type=int, default=1000, help="Number of regenerated rows per parquet shard.")
    parser.add_argument("--concurrency", type=int, default=32, help="Maximum in-flight requests against the server.")
    parser.add_argument("--max-new-tokens", type=int, default=1024)
    parser.add_argument(
        "--temperature",
        type=float,
        default=0.0,
        help="Default 0.0 = greedy, matches what EAGLE drafters are usually trained against.",
    )
    parser.add_argument("--top-p", type=float, default=1.0)
    parser.add_argument("--timeout-s", type=float, default=600.0, help="Per-request timeout in seconds.")
    parser.add_argument("--max-retries", type=int, default=3, help="Retries on 5xx / 429 / transport errors.")
    parser.add_argument(
        "--reasoning",
        choices=["none", "save", "disable"],
        default="none",
        help=(
            "Reasoning mode: 'none' for standard models (default), "
            "'save' to store reasoning_content from the response, "
            "or 'disable' to suppress thinking via extra_body chat_template_kwargs."
        ),
    )
    parser.add_argument(
        "--resume", action="store_true", help="Skip shard indices whose parquet file already exists in --output-dir."
    )
    parser.add_argument("--log-level", default="INFO")
    return parser


def main(argv: list[str] | None = None) -> int:
    """CLI entry point. Parses ``argv`` and returns the process exit code."""
    args = _build_parser().parse_args(argv)
    logging.basicConfig(
        level=getattr(logging, args.log_level.upper(), logging.INFO),
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    return asyncio.run(_run(args))


if __name__ == "__main__":
    sys.exit(main())
