# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# To run this recipe, please use the following command:
# torchrun --nproc-per-node=8 examples/llm_finetune/finetune.py --config examples/llm_finetune/nemotron/llama3_3_nemotron_super_49B_squad.yaml
# This recipe is validated on 2 8xH100 nodes.


recipe: TrainFinetuneRecipeForNextTokenPrediction

step_scheduler:
  global_batch_size: 16
  local_batch_size: 2
  ckpt_every_steps: 100
  val_every_steps: 100  # will run every x number of gradient steps
  max_steps: 100

dist_env:
  backend: nccl
  timeout_minutes: 20

rng:
  _target_: nemo_automodel.components.training.rng.StatefulRNG
  seed: 1111
  ranked: true

model:
  _target_: nemo_automodel.NeMoAutoModelForCausalLM.from_pretrained
  pretrained_model_name_or_path: nvidia/Llama-3_3-Nemotron-Super-49B-v1_5
  trust_remote_code: true
  attn_implementation: flash_attention_2

# torch.compile configuration
compile:
  enabled: false
  mode: "default"  # Options: "default", "reduce-overhead", "max-autotune"
  fullgraph: false
  dynamic: true  # Set to false for better performance with fixed shapes
  backend: null  # Use default backend (inductor)

distributed:
  strategy: fsdp2
  dp_size: none
  tp_size: 4
  cp_size: 1
  ep_size: 1
  pipeline:
    pp_microbatch_size: 1
    pp_schedule: interleaved1f1b
    scale_grads_in_schedule: false
  pp_size: 2
  sequence_parallel: false

checkpoint:
  enabled: true
  checkpoint_dir: checkpoints/
  model_save_format: safetensors
  save_consolidated: final

loss_fn:
  _target_: nemo_automodel.components.loss.masked_ce.MaskedCrossEntropy

dataset:
  _target_: nemo_automodel.components.datasets.llm.squad.make_squad_dataset
  dataset_name: rajpurkar/squad
  split: train
  seq_length: 1024
  padding: max_length
  truncation: true

packed_sequence:
  packed_sequence_size: 0

dataloader:
  _target_: torchdata.stateful_dataloader.StatefulDataLoader
  collate_fn: nemo_automodel.components.datasets.utils.default_collater
  shuffle: True
  drop_last: True

validation_dataset:
  _target_: nemo_automodel.components.datasets.llm.squad.make_squad_dataset
  dataset_name: rajpurkar/squad
  split: validation
  limit_dataset_samples: 64
  seq_length: 1024
  padding: max_length
  truncation: true

validation_dataloader:
  _target_: torchdata.stateful_dataloader.StatefulDataLoader
  collate_fn: nemo_automodel.components.datasets.utils.default_collater
  shuffle: True
  drop_last: True

optimizer:
  _target_: torch.optim.Adam
  betas: [0.9, 0.999]
  eps: 1e-8
  lr: 1.0e-5
  weight_decay: 0

lr_scheduler:
  lr_decay_style: cosine
  min_lr: 1.0e-6

ci:
  recipe_owner: akoumpa
  nodes: 2
  time: "00:45:00"
  vllm_deploy: true
  checkpoint_robustness:
    hf_kl_threshold: 5e-3
    resume_loss_threshold: 5e-2
    distributed.tp_size: 8
    tokenizer_name: nvidia/Llama-3_3-Nemotron-Super-49B-v1_5
    hf_device_map_auto: true
    trust_remote_code: true
    dataset.limit_dataset_samples: 500
    validation_dataset.limit_dataset_samples: 500
